language: ruby
sudo: false
cache: bundler
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
env:
  global:
    - CODECLIMATE_REPO_TOKEN=5149a81a58ceefa61850827c29b5fecc303d15c038b7ad4fb12e8279d2be47ab
matrix:
  fast_finish: true
  allow_failures:
    - ruby-head

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d347d6c0296c3caf01ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
